#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

$application = new Application();
$application->add(new sat8bit\RoombaSim\RoombaSimulatorCommand);
$application->run();
